services:
  bot:
    container_name: weatherbot
    build: .
    image: virtualwolf/weatherbot:latest
    restart: unless-stopped
    volumes:
      - ./config.json:/opt/service/config.json
      - ./facts.json:/opt/service/facts.json
